- cookbooks/env_motd/README.md
- cookbooks/env_motd/metadata.rb
- cookbooks/env_motd/recipes/bash.rb
- cookbooks/env_motd/recipes/default.rb
- cookbooks/env_motd/recipes/motd.rb
- cookbooks/env_motd/templates/default/bashrc.erb
- cookbooks/env_motd/templates/default/motd.erb
- cookbooks/main/recipes/default.rb
Add some stuff to ssh login and bash shell line
> motd & bash shell customization

- cookbooks/sidekiq/files/default/sidekiq
* Loads env.custom if it exists
* Preserves environment when calling sudo (sudo -E)
> Sidekiq runner honors env.custom

- cookbooks/elasticsearch/attributes/default.rb
Update Elastic Search to 1.4.5
> Update Elastic Search to 1.4.5

- cookbooks/redis-yml/README.md
> Update README.md for redis-yml

- cookbooks/mongodb/templates/default/mongo-backup.rb.erb
> add require for json to mongo backup script

- cookbooks/sidekiq/readme.md
Some customers reported stale workers running from previous version being left around. The deploy hooks here are the ones that solved the issue.
> Update recommended deploy hook for restarting sidekiq

- cookbooks/rds/attributes/default.rb
- cookbooks/rds/recipes/default.rb
> Use node[:applications] and add examples to the rds cookbook

- cookbooks/solr/files/default/solr.logrotate
- cookbooks/solr/recipes/default.rb
Settings can be modified on solr/files/default/solr.logrotate
> Added logrotation for Solr

- cookbooks/db_restore/README.md
- cookbooks/db_restore/attributes/db_restore.rb
- cookbooks/db_restore/recipes/default.rb
- cookbooks/db_restore/templates/default/download.yml.erb
- cookbooks/db_restore/templates/default/download_backup.sh.erb
- cookbooks/main/recipes/default.rb
add cookbook to assist with downloading and restoring databases via eybackup
> add db_restore cookbook

- cookbooks/delayed_job4/README.markdown
- cookbooks/delayed_job4/recipes/default.rb
- cookbooks/delayed_job4/templates/default/dj.erb
- cookbooks/delayed_job4/templates/default/dj.monitrc.erb
Remove unnecessary code for old delayed_job versions
> Create a recipe for delayed_job 4

- cookbooks/php55/attributes/default.rb
- cookbooks/php55/files/default/eselect-php-0.9.1.ebuild
- cookbooks/php55/files/default/memcache.ini
- cookbooks/php55/files/default/mongo.ini
- cookbooks/php55/files/default/php-5.5.32-r2.ebuild
- cookbooks/php55/files/default/php-7.0.4-r1.ebuild
- cookbooks/php55/files/default/redis.ini
- cookbooks/php55/recipes/setup_portage.rb
fix execute
fix memcache install
add force
more pecl fixes
add php extensions
add comment
> add new php extensions

- cookbooks/sunspot/README.md
> Deprecate the sunspot cookbook

- cookbooks/datadog/templates/default/datadog.conf.erb
removed duplicate disable_file_logging: True
> datadog configuration template fix per CC-1002

- cookbooks/elasticsearch/attributes/default.rb
- cookbooks/elasticsearch/recipes/default.rb
- cookbooks/elasticsearch/recipes/non_util.rb
Set default version to 1.7.5.  
Changed download URL to accomodate all released 1.x versions.
> Upgrading default installed version to 1.7.5.

- cookbooks/elasticsearch/libraries/engineyard.rb
- cookbooks/elasticsearch/recipes/default.rb
- cookbooks/elasticsearch/recipes/non_util.rb
- cookbooks/elasticsearch/recipes/s3_bucket.rb
> Remove dnapi from the elasticsearch recipe

- cookbooks/flume/README.md
- cookbooks/flume/attributes/default.rb
- cookbooks/flume/files/default/flume-stop.sh
- cookbooks/flume/files/default/flume.monitrc
- cookbooks/flume/files/default/log4j.properties
- cookbooks/flume/recipes/default.rb
- cookbooks/flume/templates/default/flume-start.sh.erb
- cookbooks/flume/templates/default/flume.conf.erb
For log aggregation. See https://flume.apache.org/
> Adds the Flume recipe

- cookbooks/sidekiq/attributes/default.rb
- cookbooks/sidekiq/recipes/setup.rb
- cookbooks/sidekiq/templates/default/sidekiq.erb
> Add a timeout parameter to /engineyard/bin/sidekiq

- cookbooks/sidekiq/attributes/default.rb
- cookbooks/sidekiq/readme.md
- cookbooks/sidekiq/recipes/setup.rb
> Sidekiq: Add memory limit in attributes file

- cookbooks/collectd/readme.md
Current README.MD for collectd recipe is incomplete, this PR is to fix it
Inside recipes folder for collectd the string parameter can be found
> Fixing readme file for collectd recipe

- cookbooks/newrelic_infra/README.md
- cookbooks/newrelic_infra/attributes/default.rb
- cookbooks/newrelic_infra/files/default/newrelic_infra.monitrc
- cookbooks/newrelic_infra/libraries/newrelic_helpers.rb
- cookbooks/newrelic_infra/recipes/default.rb
- cookbooks/newrelic_infra/templates/default/newrelic-infra.erb
- cookbooks/newrelic_infra/templates/default/newrelic-infra.yml.erb
This cookbook sets up the New Relic Infrastructure agent. Please check the README for more details.
> Initial version of the New Relic Infra recipe

- cookbooks/solr/README.md
Add instructions on how to manually create a core and copy the sunspot configuration files
> Update Solr recipe README

- cookbooks/imagemagick/files/default/policy.xml
Updated policy.xml to address imagemagick vulnerability GLSA 201611-21
> updated policy.xml
