- cookbooks/elasticsearch/README.md
- cookbooks/elasticsearch/attributes/default.rb
- cookbooks/elasticsearch/recipes/default.rb
- cookbooks/elasticsearch/recipes/non_util.rb
- cookbooks/elasticsearch/templates/default/elasticsearch.in.sh.erb
NOTE: This recipe installs Elasticsearch 1.4 and requires Java 7 or later. It will only work on the Gentoo 12.11 stack; the Java 7 ebuild is not available on Gentoo 2009. We do not recommend running older versions of Elasticsearch - versions prior to 1.2 have a remote code execution vulnerability, see http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2014-3120
Summary of changes
* Load the Java package name and version to install from attributes so that it’s easier to modify later
* Default Java is dev-java/icedtea-bin version 7.2.3.3-r1
* Run eselect after installing Java to ensure that the correct JDK is set
* Increase Java stack size when running Elasticsearch to 256k (needed by newer version of Elasticsearch, see * https://groups.google.com/forum/#!topic/elasticsearch/cfihFvFg08Q)
* …
> [CC-716] Update the elasticsearch recipe to use Java 7 and Elasticsearch 1.4.0

- cookbooks/sidekiq/readme.md
Sometimes, sidekiq worker processes don't be killed to use monit restart due to monit is single thread application. 
I replace the document it goes well.
> change the document of restarting sidekiq

- cookbooks/sidekiq/recipes/cleanup.rb
Currently when applying the recipes the sidekiq cleanup never runs on actual sidekiq servers because of what I assume is a `if` `unless` mixup.
If we run 2 sidekiq workers by changing the YML file as follows
```yml
:workers => 2,
```
And then in the future decrease the worker count - the processes will never be killed resulting in floating workers not monitored by monit and never update to run the up to date code.
This fixes that by making sure that the cleanup code is run correctly.
> Fix Sidekiq cleanup

- cookbooks/jenkins/files/default/nginx.jetty.conf
- cookbooks/jenkins/recipes/default.rb
- cookbooks/jenkins/recipes/jetty_install.rb
- fixing the jenkins link issues
- upgrade jetty to last stable version
Low
Jetty, Nginx
Creating an environment which be installed jenkins, and then access jenkins url and click "Manage Jenkins" and do browser back.
- To create an environment and upload and apply the recipes with including "jenkins recipe"
https://github.com/engineyard/ey-cloud-recipes/blob/master/cookbooks/jenkins/README.md
> correct the header to jenkins and upgrade jetty's version

- Rakefile
Description of your patch
-------------
Fix Rakefile for Windows users
Recommended Release Notes
-------------
Minor fix for Windows users
Estimated risk
-------------
Low
Components involved
-------------
Rakefile
Description of testing done
-------------
`rake new_cookbook COOKBOOK=test_recipe` on OS X, Linux and Windows.
QA Instructions
-------------
Locate a Windows computer or VM
Install Ruby on it (http://railsinstaller.org/en has an installer that includes Git)
Clone ey-cloud-recipes locally
run `rake new_cookbook COOKBOOK=test_recipe` 
Verify it completes successfully (previously complained ` /p is not a valid flag`)
> [Support-753] Fix Rakefile for Windows users

- cookbooks/thinking-sphinx-3/README.md
I received a message that `shared_path`, `current_path`, and `environment` were all deprecated in favor of `config.shared_path`, `config.current_path`,  and `config.environment`. I made changes in the README to use the preferred methods.
> changed deprecated code in readme to current implementation

- cookbooks/main/recipes/default.rb
- cookbooks/postgresql9_extensions/README.md
- cookbooks/postgresql9_extensions/definitions/pg_stat_statements.rb
- cookbooks/postgresql9_extensions/recipes/ext_autoexplain.rb
* Adds needed the config params needed to properly enable the pg_stat_statements extension
* Restarts the db process to complete the extension enabling
* Adds warnings in documentation that the extension requires a process restart
> properly installs pg_stat_statements extension

- cookbooks/monit_disable/README.md
- cookbooks/monit_disable/recipes/default.rb
This is a new recipe for disabling unwanted services that we install on instances by default (e.g. memcached, redis)
> Add monit_disable recipe for CC-509

- cookbooks/main/libraries/ey_release_version.rb
- cookbooks/main/recipes/default.rb
- cookbooks/postgresql9_extensions/definitions/postgis.rb
- cookbooks/postgresql9_extensions/definitions/postgis2.rb
- cookbooks/postgresql9_extensions/recipes/ext_postgis2_install.rb
* postgis 2.1.5 for pg 9.3/9.4 on 12.11
* Add ey_release_version helper method in main cookbook's libraries
* Fix postgis 2.1.1 installs on 9.3/2009a and 9.2/12.11
* Tweaks to abort execution if chosen postgis version isn't supported
for current Postgres version and/or environment stack
> Fix Postgis recipes

- cookbooks/eybackup_slave/recipes/default.rb
Uses a return instead of a raise and prints a log message to the chef log.
> prevent exception in eybackup_slave when backups are disabled in an environment

- cookbooks/redis/README.md
- cookbooks/redis/recipes/default.rb
Turns out that for a Rails app having an underscore in the hostname portion of the host definition is not handled well. This recipe worked properly with `redis_instance` in one Node.js app and in the Rails console.
> Change `/etc/hosts` mapping for Redis host to `redis-instance`

- cookbooks/delayed_job/README.markdown
Added specific examples on how to add the monit restart command in a deploy hook
> delayed_job recipe: Improve README section on deploy hooks

- cookbooks/mongodb/templates/default/mongo-backup.rb.erb
Backups were silently failing because `env ruby` doesn't usually have aws-s3 gem installed. Additionally, the most recent version of Mongo wasn't compatible with how we were identifying databases to backup.
> direct mongo backups to use ey_resin ruby, and update db capture to be compatible with latest mongo

- cookbooks/jenkins/recipes/jetty_install.rb
I used the latest Jetty 8.1.x release
http://download.eclipse.org/jetty/
> Update Jetty download path

- cookbooks/cron/recipes/default.rb
This avoids a false match on unnamed instances like app_master and db_master
> Use equality to determine the matching node name

- cookbooks/thinking-sphinx-3/recipes/thinking_sphinx.rb
thinking_sphinx.yml should symlink from the deployed repo to the shared config area, should it not?
> Reversing thinking_sphinx symlink direction

- cookbooks/delayed_job/README.markdown
The base fork has a typo for the hook which causes deployments to fail when copied and pasted. This patch fixes that missing '_'.
> Documentation: fixes typo in deploy hook note for delayed_job

- cookbooks/papertrail/README.md
- cookbooks/papertrail/recipes/default.rb
- cookbooks/papertrail/templates/default/log_files.yml.erb
- cookbooks/papertrail/templates/default/remote_syslog.confd.erb
- cookbooks/papertrail/templates/default/remote_syslog.initd.erb
- cookbooks/papertrail/templates/default/syslog-ng.conf.erb
This PR has the following changes:
* Incorporates latest changes from https://github.com/leonsodhi/ey-cloud-recipes/tree/master/cookbooks/papertrail
* Adds a README
* Downloads remote_syslog using wget because Github returns HTTP 403 when we try to download remote_syslog with Chef remote_file
* Removes the pidfile from DAEMON_ARGS so that it's not referenced twice in conf.d
This PR also includes the changes in https://github.com/engineyard/ey-cloud-recipes/pull/169 and https://github.com/engineyard/ey-cloud-recipes/pull/166 so those PRs can be closed when this is merged in.
> Update the Papertrail recipe

- cookbooks/redis/README.md
- cookbooks/redis/attributes/default.rb
- cookbooks/redis/recipes/default.rb
The default utility name for redis chef recipe now configurable like sidekiq and sphinx recipes.
> Allows easier configuration of redis instance name

- cookbooks/solr/recipes/default.rb
The previous URL for Solr 4.10.2 is no longer available
> Updated the Solr URL to 4.10.4

- cookbooks/sidekiq/files/default/sidekiq
Occasionally, it will appear that `sidekiq` is not writing a pid
file for the worker that it spawns. What's actually happening is
that the pid file is being written before the `rm -f "${pid_file}"`
that runs before sidekiq has been fully synced to disk, so it's
being written, but then its file dscriptor is being removed from the
file system.
This makes monit think that the worker is not running, so it starts
another.
This change just adds a 10-second sleep immediately after the
pid file removal to (hopefully) ensure that the file does not
get blown away immediately upon writing.
> Avoid filesystem race condition for sidekiq

- cookbooks/shared_db/recipes/default.rb
This update makes things easier for people with more than two apps in an environment able to share a single database. Also discourages the use of keep files and deploy hooks in applications so big win there :wink:
> Updated shared_db to account for multi-app environment

- cookbooks/passenger_monitor/README.md
- cookbooks/passenger_monitor/attributes/default.rb
- cookbooks/passenger_monitor/files/default/passenger_monitor4
- cookbooks/passenger_monitor/recipes/default.rb
This includes a modified passenger_monitor4 that sends a kill -9 to terminate frozen workers.
See https://github.com/radamanthus/ey-cloud-recipes/blob/passenger_monitor/cookbooks/passenger_monitor/README.md for details
> Add a custom chef for passenger_monitor4

- cookbooks/datadog/attributes/default.rb
- cookbooks/datadog/files/default/datadog.monitrc
- cookbooks/datadog/files/default/datadog_wrapper.sh
- cookbooks/datadog/files/default/setup_agent.sh
- cookbooks/datadog/recipes/config.rb
- cookbooks/datadog/recipes/daemonize.rb
- cookbooks/datadog/recipes/default.rb
- cookbooks/datadog/recipes/finish.rb
- cookbooks/datadog/recipes/install.rb
- cookbooks/datadog/recipes/nginx.rb
- cookbooks/datadog/templates/default/custom.txt.erb
- cookbooks/datadog/templates/default/datadog.conf.erb
- cookbooks/datadog/templates/default/nginx.yaml.erb
This recipe adds support for datadog and the nginx integration on EY.
Would love some feedback
Running 3 Ruby on Rails Solo EY instances
You need to add your datadog api key to the `attributes/default.rb` 
`default['datadog']['api_key'] = "" `
If not already included, add:
`include_recipe 'datadog` to the main recipes folder
1. remove the comments in `recipes/default.rb` 
2. You need to add the directory where your custom nginx files are, to the `attributes/default.rb` 
3. add the nginx integration in the datadog control panel.
> datadog support

- cookbooks/le/templates/default/logentries.initd.erb
--oknodo params is deprecated and crashed logentries when stop application.
```
$ sudo /etc/init.d/logentries stop
* Stopping Logentries Agent ...
* WARNING: -o/--oknodo is deprecated and will be removed in the future
* start-stop-daemon: no matching processes found                                                                                                                                                                                                                         [ !! ]
* ERROR: logentries failed to stop
```
I removed and my instances are green.
> Remove --oknodo from LE recipe.

- cookbooks/delayed_job/recipes/default.rb
- cookbooks/delayed_job/templates/default/dj.erb
Instead of waiting for https://github.com/engineyard/ey_monit_scripts/blob/master/engineyard/bin/dj to get fixed, we updated the delayed_job recipe to overwrite /engineyard/bin/dj.
The dj.erb template simply changes the following compared to the dj from ey_monit_scripts:
```
added line 4:
< # This script is created by the delayed_job recipe
changed line 182:
<            kill -9 $PID $WORKER_PID 2>/dev/null; true
---
>            kill -9 $PID 2>/dev/null; true
```
Note about testing:
For testing, I setup a v4 environment, deployed the todo app, and enabled and applied the delayed_job recipe. I've confirmed that the delayed job workers were setup (through monit). Monit stop and start works. Also confirmed that the /engineyard/bin/dj was overwritten by the recipe with the new kill command. …
> [CC-920] Overwrite /engineyard/bin/dj with own template (fix kill command)

- cookbooks/delayed_job4/README.markdown
users should include delayed_job4, not delayed_job, in main recipes.
> fix readme setup instructions

- cookbooks/imagemagick/README.md
- cookbooks/imagemagick/files/default/imagemagickkeywords
- cookbooks/imagemagick/files/default/imagemagickunmask
- cookbooks/imagemagick/files/default/policy.xml
- cookbooks/imagemagick/recipes/default.rb
This is to address CVE-2016-5118 and CVE-2016-3714
czimmerman's imagemagick branch fell behind master and merging that will result in too many changes. I cherry-picked the changes from that branch and added a README to create this PR.
> Add the imagemagick cookbook to address recent vulnerabilities

- cookbooks/api-keys-yml/README.md
- cookbooks/rails-secrets/README.md
- cookbooks/rails-secrets/recipes/default.rb
- cookbooks/rails-secrets/templates/default/secrets.yml.erb
Rails 4.1 introduced secrets.yml which does part of what api-keys-yml is meant for. rails-secrets is a simplified version of api-keys-yml and includes instructions specific to Rails applications.
api-keys-yml is still useful for non-Rails or pre-Rails 4.1 applications.
This PR also includes a pointer from api-keys-yml's README to the rails-secrets recipe.
> Add the rails-secrets recipe

- cookbooks/datadog/files/default/datadog.monitrc
- cookbooks/datadog/files/default/datadog_wrapper.sh
- cookbooks/datadog/files/default/setup_agent.sh
- cookbooks/datadog/files/default/supervisord.conf
- cookbooks/datadog/recipes/config.rb
- cookbooks/datadog/recipes/daemonize.rb
- cookbooks/datadog/recipes/default.rb
- cookbooks/datadog/recipes/finish.rb
- cookbooks/datadog/recipes/install.rb
- cookbooks/datadog/recipes/postgres.rb
This addresses item #1 in https://github.com/engineyard/ey-cloud-recipes/issues/279
Changes:
* Installs datadog to `/home/deploy/datadog` instead of `/root/datadog`
* Runs datadog and supervisor as the deploy user instead of the root user
> Run datadog as the deploy user

- cookbooks/redis/recipes/default.rb
redis_instance should be the first instance named "redis", not the first instance with a name that matches /redis/.
For environments with a redis_backup or redis_slave instance, the match check might pick up these instances instead.
> Minor bugfix on redis recipe

- cookbooks/redis/README.md
- cookbooks/redis/recipes/default.rb
- cookbooks/redis/templates/default/redis.monitrc.erb
This will let V4 customers run Redis 3.2.3 which supports clustering
The PR _does not_ include changes to support clustering.
> Modify Redis recipe to install from source

- cookbooks/redis/recipes/default.rb
Download Redis installer in /opt. 
https://github.com/engineyard/ey-cloud-recipes/issues/301
> Patch for Issue #301

- cookbooks/classiclink/README.md
- cookbooks/classiclink/attributes/classiclink.rb
- cookbooks/classiclink/attributes/credentials.rb
- cookbooks/classiclink/recipes/classiclink.rb
- cookbooks/classiclink/recipes/default.rb
- cookbooks/classiclink/recipes/install.rb
- cookbooks/classiclink/templates/default/aws.config.erb
- cookbooks/classiclink/templates/default/aws.credentials.erb
- cookbooks/main/recipes/default.rb
Adds cookbook to automate Classiclinking of EC2 Classic instances to manually created VPCs for peering purposes.
> Adding Classiclink cookbook

- cookbooks/redis/templates/default/redis-3.2.conf.erb
Allow customers to shoot themselves in the foot.  This basically reverts
the default behavior of redis 2.8 and other lower versions of Redis.
> Disable protected-mode

- cookbooks/shared_db/recipes/default.rb
fixes #308 where parent database credentials would be overwritten by a child's.
> Generate keep files for shared databases

- cookbooks/main/recipes/default.rb
default.rb lacked the aws_cli install lines
> adding aws installation lines to cookbooks/main/recipes/default.rb

- cookbooks/db_client_libs/recipes/default.rb
When using the `db_client_libs` recipe with pg 9.5.5 it was failing for instances that didn't have `/data/src` folder.
The issue was that it was trying to create a directory `/data/src/postgresql` but parent folder `/data/src` didn't exist.
To fix that we have used the `recursive true` option
The PR also strips non meaningful whitespace and fixes no new line at the end of file issue. To simplify review please add `?w=0` flag to the PR url like https://github.com/engineyard/ey-cloud-recipes/pull/314/files?w=0
1. Try to apply the cookbook on an instance without `/data/src` folder
**Current result:** It fails
**Expected result:** Recipe is applied successfully
> Fixes db_client_libs issue for pg 9.5.5 when `/data/src` folder doesn't exist

- README.md
Add a note in README to link to the documentation for Migrating Custom Chef Recipes from V4 to V5.
> Update README to link to Migrating Recipes To V5 doc.

- cookbooks/delayed_job4/README.markdown
- cookbooks/delayed_job4/attributes/default.rb
- cookbooks/delayed_job4/recipes/default.rb
- cookbooks/delayed_job4/templates/default/dj.monitrc.erb
Description of your patch
-------------
This change makes the DJ worker memory limit in the monit control file customizable through delayed_job4/attributes/default.rb. Other settings (worker_count and is_dj_instance) were moved from delayed_job4/recipes/default.rb to delayed_job4/attributes/default.rb.
How to Test
-------------
Enable the updated delayed_job4 recipe, and try changing the value of `default['delayed_job4']['worker_memory']` in attributes/default.rb. Check that the memory limit in /etc/monit.d/delayed_job*.monitrc gets updated on Apply.
Also, try changing `default['delayed_job4']['is_dj_instance']` to only apply to solo:
```ruby
default['delayed_job4']['is_dj_instance'] = node[:instance_role] == "solo" #|| (node[:instance_role] == "util" && node[:name] !~ …
```
> DJ worker memory limit and other settings in attributes.

- cookbooks/delayed_job4/attributes/default.rb
Description of your patch
-------------
Fixes #230. This change adds default values for worker count for additional, newer instance types.
How to Test
-------------
Use delayed_job4 custom chef recipe. Make sure is_dj_instance attribute uses default value that also sets up DJ in utility instances named "delayed_job". Try adding utility instances named "delayed_job" with various instance types (t2, r3, r4) and compare to the default values in delayed_job4/attributes/default.rb.
> DJ: Add default worker count for new instance types.

- cookbooks/le/files/default/le-1.4.25.ebuild
Changing "logentries" to "rapid7" on ebuild file
N/A
Low
files/default/le-1.4.25.ebuild
See QA instructions
No QA needed
> changing logentries to rapid7 on ebuild file

- cookbooks/flume/recipes/default.rb
- cookbooks/flume/templates/default/flume.conf.erb
The agent name in the configuration should be the same as the agent name used by the start script (https://github.com/engineyard/ey-cloud-recipes/blob/master/cookbooks/flume/templates/default/flume-start.sh.erb)
> Bugfix: Flume recipe: Use AWS instance id as agent name

- cookbooks/elasticsearch/attributes/default.rb
Needed to address multiple JDK vulnerabilities (see https://security.gentoo.org/glsa/201701-43)
> Use IcedTea 7.2.6.8 for Elasticsearch

- cookbooks/jenkins/recipes/jetty_install.rb
Fix Jetty version for Jenkins, the currently recipe is not being successfully when applied.
Low
Jenkins recipe
> Fix Jetty version for Jenkins recibe

- cookbooks/sidekiq/recipes/setup.rb
This part is prone to timing errors, causing chef failures
and sidekiq::cleanup already restarts sidekiq even without the monit reload and restart
> Sidekiq: Remove monit restart in sidekiq::setup

- cookbooks/delayed_job4/templates/default/dj.erb
Backport changes made in V5 to improve worker termination
- Make sure DJ workers do not become orphans (https://github.com/engineyard/ey-cookbooks-stable-v5/pull/224)
- Add a check for zombie DJ workers (https://github.com/engineyard/ey-cookbooks-stable-v5/pull/251, https://github.com/engineyard/ey-cookbooks-stable-v5/pull/265)
> [delayed_job4] Update dj.erb

- cookbooks/custom_nodejs/README.md
- cookbooks/custom_nodejs/attributes/default.rb
- cookbooks/custom_nodejs/files/default/nodejs-bin-generic.ebuild
- cookbooks/custom_nodejs/recipes/default.rb
- cookbooks/main/recipes/default.rb
This custom recipe installs nodejs of the selected version, even if this version does not exist in portage.
N/A
Low
README
In a v4 stack environment the recipe "custom_nodejs" was applied (for node-v10.12.0). The result was:
```
ip-10-0-0-77 ~ # node -v
v10.12.0
ip-10-0-0-77 ~ # npm -v
6.4.1
```
1. select the nodejs version to install in `attributes/default.rb`. Do not use an already existing version in portage, as it will just fail. 
2. uncomment the line `include_recipe "custom_nodejs"` in `main/recipes/default.rb` in order to include the "custom_nodejs" recipe in the chef run
3. upload and apply the recipes in your v4 environment
4. check the version of nodejs via `node-v`, `eselect nodejs list` and `eix net-libs/nodejs-bin`
> Custom nodejs recipe

- cookbooks/fail2ban/attributes/default.rb
- cookbooks/fail2ban/recipes/default.rb
Corrected a typo on /recipes/default.rb
Added missing action on /attributes/default.rb for nginx-dos
N/A
Low
/recipes/default.rb
/attributes/default.rb
See QA instructions
No QA needed
> Fail2ban address typo on default.rb and added missing action on nginx-dos jail
